---
- name: Cloning dotfiles
  git:
    repo: "https://github.com/narzac/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/code/personal/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: true
    version: main
  become: false

- name: Install dotfiles
  shell: cd $HOME/code/personal/dotfiles && make install
